/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProfiloRouteImport } from './routes/_app.profilo'
import { Route as AppMappaRouteImport } from './routes/_app.mappa'
import { Route as AppInsightRouteImport } from './routes/_app.insight'
import { Route as AppFrameworkRouteImport } from './routes/_app.framework'
import { Route as AppDiarioRouteImport } from './routes/_app.diario'
import { Route as AppChatRouteImport } from './routes/_app.chat'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfiloRoute = AppProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppRoute,
} as any)
const AppMappaRoute = AppMappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightRoute = AppInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => AppRoute,
} as any)
const AppFrameworkRoute = AppFrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/chat': typeof AppChatRoute
  '/diario': typeof AppDiarioRoute
  '/framework': typeof AppFrameworkRoute
  '/insight': typeof AppInsightRoute
  '/mappa': typeof AppMappaRoute
  '/profilo': typeof AppProfiloRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AppChatRoute
  '/diario': typeof AppDiarioRoute
  '/framework': typeof AppFrameworkRoute
  '/insight': typeof AppInsightRoute
  '/mappa': typeof AppMappaRoute
  '/profilo': typeof AppProfiloRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/diario': typeof AppDiarioRoute
  '/_app/framework': typeof AppFrameworkRoute
  '/_app/insight': typeof AppInsightRoute
  '/_app/mappa': typeof AppMappaRoute
  '/_app/profilo': typeof AppProfiloRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/diario'
    | '/framework'
    | '/insight'
    | '/mappa'
    | '/profilo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/diario'
    | '/framework'
    | '/insight'
    | '/mappa'
    | '/profilo'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/chat'
    | '/_app/diario'
    | '/_app/framework'
    | '/_app/insight'
    | '/_app/mappa'
    | '/_app/profilo'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profilo': {
      id: '/_app/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof AppProfiloRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mappa': {
      id: '/_app/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof AppMappaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insight': {
      id: '/_app/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof AppInsightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/framework': {
      id: '/_app/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof AppFrameworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario': {
      id: '/_app/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppFrameworkRoute: typeof AppFrameworkRoute
  AppInsightRoute: typeof AppInsightRoute
  AppMappaRoute: typeof AppMappaRoute
  AppProfiloRoute: typeof AppProfiloRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppFrameworkRoute: AppFrameworkRoute,
  AppInsightRoute: AppInsightRoute,
  AppMappaRoute: AppMappaRoute,
  AppProfiloRoute: AppProfiloRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
