/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProfiloRouteImport } from './routes/_app.profilo'
import { Route as AppPauseRouteImport } from './routes/_app.pause'
import { Route as AppMappaRouteImport } from './routes/_app.mappa'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppInsightRouteImport } from './routes/_app.insight'
import { Route as AppFrameworkRouteImport } from './routes/_app.framework'
import { Route as AppDiarioRouteImport } from './routes/_app.diario'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfiloRoute = AppProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppRoute,
} as any)
const AppPauseRoute = AppPauseRouteImport.update({
  id: '/pause',
  path: '/pause',
  getParentRoute: () => AppRoute,
} as any)
const AppMappaRoute = AppMappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightRoute = AppInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => AppRoute,
} as any)
const AppFrameworkRoute = AppFrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chat': typeof AppChatRoute
  '/diario': typeof AppDiarioRoute
  '/framework': typeof AppFrameworkRoute
  '/insight': typeof AppInsightRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/mappa': typeof AppMappaRoute
  '/pause': typeof AppPauseRoute
  '/profilo': typeof AppProfiloRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chat': typeof AppChatRoute
  '/diario': typeof AppDiarioRoute
  '/framework': typeof AppFrameworkRoute
  '/insight': typeof AppInsightRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/mappa': typeof AppMappaRoute
  '/pause': typeof AppPauseRoute
  '/profilo': typeof AppProfiloRoute
  '/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/diario': typeof AppDiarioRoute
  '/_app/framework': typeof AppFrameworkRoute
  '/_app/insight': typeof AppInsightRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/mappa': typeof AppMappaRoute
  '/_app/pause': typeof AppPauseRoute
  '/_app/profilo': typeof AppProfiloRoute
  '/_app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/chat'
    | '/diario'
    | '/framework'
    | '/insight'
    | '/knowledge'
    | '/mappa'
    | '/pause'
    | '/profilo'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/chat'
    | '/diario'
    | '/framework'
    | '/insight'
    | '/knowledge'
    | '/mappa'
    | '/pause'
    | '/profilo'
    | '/'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/_app'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/chat'
    | '/_app/diario'
    | '/_app/framework'
    | '/_app/insight'
    | '/_app/knowledge'
    | '/_app/mappa'
    | '/_app/pause'
    | '/_app/profilo'
    | '/_app/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profilo': {
      id: '/_app/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof AppProfiloRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pause': {
      id: '/_app/pause'
      path: '/pause'
      fullPath: '/pause'
      preLoaderRoute: typeof AppPauseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mappa': {
      id: '/_app/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof AppMappaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insight': {
      id: '/_app/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof AppInsightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/framework': {
      id: '/_app/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof AppFrameworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario': {
      id: '/_app/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppFrameworkRoute: typeof AppFrameworkRoute
  AppInsightRoute: typeof AppInsightRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMappaRoute: typeof AppMappaRoute
  AppPauseRoute: typeof AppPauseRoute
  AppProfiloRoute: typeof AppProfiloRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppFrameworkRoute: AppFrameworkRoute,
  AppInsightRoute: AppInsightRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMappaRoute: AppMappaRoute,
  AppPauseRoute: AppPauseRoute,
  AppProfiloRoute: AppProfiloRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
